### PR TITLE
Fixed `pose_lookup` and `dynamic_lib`

### LINKED ISSUE #303: `pose_lookup` initialization is buggy
Fix the constructor initialization list in `ILLIXR/pose_lookup/plugin.cpp` to use the appropriate default values (e.g. `Eigen::Matrix3f::Zero()`).

### PR DESCRIPTION
**Pull request by e3m3**
Closes #303 .
- Fixed `pose_lookup` initialization in `pose_lookup/plugin.cpp`
- Added debugging prints to `common/dynamic_lib.hpp`
- New `path_basename` for debugging in `common/dynamic_lib.hpp`
- Failed calls to `dlclose` non-fatal with `dbg` in `common/dynamic_lib.hpp`

### CODE REVIEW

**Review by charmoniumQ — COMMENTED** [review]
Imo, the `-DNDEBUG` and normal builds have deviated too far in `dynamic_lib`. One has a destructor, the other doesn't.

Can we merge the paths and always propagate debug information?

**Comment by e3m3** [comment]
Partially addresses #305 for `dbg`. Does not resolve root issue with missing symbol reference to VTK in `debugview`.

**Review by charmoniumQ — COMMENTED** [review]
I intend `dynamic_lib` to be used outside of ILLIXR, and in that case, the basename of the dirname is not so meaningful. Let's set the name to the while pathname.

Then lgtm.

File: common/dynamic_lib.hpp [hunk 1]
```diff
@@ -23,70 +25,97 @@ using void_ptr = std::unique_ptr<void, std::function<void(void*)>>;
...
+        return dynamic_lib{
+            void_ptr{handle, [](void* handle) {
+                RAC_ERRNO();
+
+                char* error;
+                int ret = dlclose(handle);
+                if ((error = dlerror()) || ret) {
+                    const std::string msg_error {"dlclose(): " + (error == nullptr ? "NULL" : std::string{error})};
+#ifndef NDEBUG
+                    /// If debugging, only report the dlclose error (non-fatal, can leak memory)
```
Comment (charmoniumQ) [inline common/dynamic_lib.hpp:84]: Why not always throw the error? The message should be pretty-printed if the exception bubbles up to the user (i.e. if it isn't caught along the way).

**Review by mhuzai — APPROVED** [review]

File: common/dynamic_lib.hpp [hunk 2]
```diff
@@ -23,70 +25,92 @@ using void_ptr = std::unique_ptr<void, std::function<void(void*)>>;
...
+                "dlsym(\"" + symbol_name + "\"): " + (error == nullptr ? "NULL" : std::string{error})
+            };
+        }
+        return symbol;
+    }
+
+    template <typename T>
+    const T get(const std::string& symbol_name) const {
+        const void* obj = (*this)[symbol_name];
+        // return reinterpret_cast<const T>((*this)[symbol_name]);
```
Comment (charmoniumQ) [inline common/dynamic_lib.hpp:107]: I believe we should use a C++-style cast here. It's more explicit because it says to reinterpret, not to dynamic or static cast.

**Review by charmoniumQ — APPROVED** [review]
