### PR TITLE
Fix RealSense plugin

### LINKED ISSUE #336: RealSense plugin crashes
ILLIXR crashes when using the D455.

### PR DESCRIPTION
**Pull request by mhuzai**
Closes #336.

### CODE REVIEW

File: realsense/plugin.cpp [hunk 1]
```diff
@@ -27,6 +27,8 @@ class realsense : public plugin {
         , _m_rgb_depth{sb->get_writer<rgb_depth_type>("rgb_depth")}
         , realsense_cam{ILLIXR::getenv_or("REALSENSE_CAM", "auto")}
         {      
+            cam_data.iteration = -1;
```
Comment (charmoniumQ) [inline realsense/plugin.cpp:30]: Is this part the fix and the rest is just renaming variables and refactoring types?

**Review by charmoniumQ — APPROVED** [review]

File: realsense/plugin.cpp (hunk 1 above)
Comment (mhuzai) [reply realsense/plugin.cpp:30]: Yup!

**Review by Boyuan-Tian — APPROVED** [review]
